.circleci/config.yml
Using the right Orbs jobs for release and build: this repository contains a library and not a gravitee plugin.
---
- use it directly by updating your project with version: `1.0.1`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.0.1/gravitee-exchange-1.0.1.zip)
=> chore: update job name for build & release

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/protocol/legacy/goodbye/GoodyeCommandAdapter.java, gravitee-exchange-connector/gravitee-exchange-connector-core/src/main/java/io/gravitee/exchange/connector/core/DefaultExchangeConnectorManager.java
With legacy protocol, the goodbye command with a reconnect:true should be ignored. Instead a Exception is thrown and then capture by the controller which lead to a websocket close.
---
- use it directly by updating your project with version: `1.0.2-adapt-goodbye-command-for-legacy-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.0.2-adapt-goodbye-command-for-legacy-SNAPSHOT/gravitee-exchange-1.0.2-adapt-goodbye-command-for-legacy-SNAPSHOT.zip)
=> fix: adapt GoodByeCommand for legacy protocol

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/controller/ControllerCommandHandlersFactory.java, gravitee-exchange-connector/gravitee-exchange-connector-core/src/main/java/io/gravitee/exchange/connector/core/DefaultExchangeConnectorManager.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/WebSocketExchangeConnector.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/channel/WebSocketConnectorChannel.java
When HelloReply's status is ERROR, throw an exception containing error detail that can be handled by the caller.
---
- use it directly by updating your project with version: `1.1.0-improve-handshake-error-handling-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.1.0-improve-handshake-error-handling-SNAPSHOT/gravitee-exchange-1.1.0-improve-handshake-error-handling-SNAPSHOT.zip)
=> feat: improve handshake error handling

gravitee-exchange-connector/gravitee-exchange-connector-websocket/pom.xml, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/WebSocketExchangeConnector.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/client/WebSocketClientConfiguration.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/client/WebSocketConnectorClientFactory.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/client/WebSocketEndpoint.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/test/java/io/gravitee/exchange/connector/websocket/WebSocketExchangeConnectorTest.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/test/java/io/gravitee/exchange/connector/websocket/client/WebSocketClientConfigurationTest.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/test/java/io/gravitee/exchange/connector/websocket/client/WebSocketConnectorClientFactoryTest.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/test/java/io/gravitee/exchange/connector/websocket/client/WebSocketEndpointTest.java, pom.xml
Just increase default max retry to 20.
---
- use it directly by updating your project with version: `1.2.0-increase-retry-default-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.2.0-increase-retry-default-SNAPSHOT/gravitee-exchange-1.2.0-increase-retry-default-SNAPSHOT.zip)
=> fix: use exponential backoff strategy for reconnection retry

gravitee-exchange-connector/gravitee-exchange-connector-core/src/main/java/io/gravitee/exchange/connector/core/DefaultExchangeConnectorManager.java, gravitee-exchange-connector/gravitee-exchange-connector-embedded/src/main/java/io/gravitee/exchange/connector/embedded/EmbeddedExchangeConnector.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/WebSocketExchangeConnector.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/ChannelManager.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelCandidateStore.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelManager.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelCandidateStoreTest.java
- list of candidate was containing duplicating id which could lead to wrong primary election
- if the primary channel is also present locally, it was first primary then secondary
- handler on connector was too late registered
- election topic was badly configured
---
- use it directly by updating your project with version: `1.2.1-fix-primary-election-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.2.1-fix-primary-election-SNAPSHOT/gravitee-exchange-1.2.1-fix-primary-election-SNAPSHOT.zip)
=> fix: rework primary channel election

gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/WebSocketExchangeConnector.java
To avoid having the delay going down, the factor must be higher than 1
---
- use it directly by updating your project with version: `1.2.1-increase-retry-factor-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.2.1-increase-retry-factor-SNAPSHOT/gravitee-exchange-1.2.1-increase-retry-factor-SNAPSHOT.zip)
=> fix: increase connector retry factor

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/command/CommandAdapter.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/command/ReplyAdapter.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/channel/AbstractWebSocketChannel.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/protocol/legacy/goodbye/GoodyeCommandAdapter.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/protocol/legacy/goodbye/LegacyGoodByeReplyAdapter.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/protocol/legacy/healthcheck/HealthCheckCommandAdapter.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/protocol/legacy/hello/HelloCommandAdapter.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/protocol/legacy/hello/HelloReplyAdapter.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/protocol/legacy/hello/LegacyHelloReplyAdapter.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/protocol/legacy/ignored/NoReplyAdapter.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/protocol/legacy/primary/PrimaryCommandAdapter.java, gravitee-exchange-api/src/test/java/io/gravitee/exchange/api/websocket/channel/test/DummyCommandAdapter.java, gravitee-exchange-api/src/test/java/io/gravitee/exchange/api/websocket/channel/test/DummyReplyAdapter.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelManager.java, gravitee-exchange-controller/gravitee-exchange-controller-embedded/src/main/java/io/gravitee/exchange/controller/embedded/channel/EmbeddedChannel.java, gravitee-exchange-controller/gravitee-exchange-controller-embedded/src/test/java/io/gravitee/exchange/controller/embedded/channel/EmbeddedChannelTest.java
In some case legacy installation wasn't providing any target id as it was hold by the handler itself. Adding the target id param will help adapting some commands.
---
- use it directly by updating your project with version: `1.2.3-add-target-id-on-adapters-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.2.3-add-target-id-on-adapters-SNAPSHOT/gravitee-exchange-1.2.3-add-target-id-on-adapters-SNAPSHOT.zip)
=> Add target id on adapters

gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/WebSocketExchangeConnector.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/client/WebSocketClientConfiguration.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/client/WebSocketEndpoint.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/test/java/io/gravitee/exchange/connector/websocket/client/WebSocketConnectorClientFactoryTest.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/test/java/io/gravitee/exchange/connector/websocket/client/WebSocketEndpointTest.java
Handle endpoint url containing underscore
---
- use it directly by updating your project with version: `1.2.5-fix-websocket-endpoint-creation-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.2.5-fix-websocket-endpoint-creation-SNAPSHOT/gravitee-exchange-1.2.5-fix-websocket-endpoint-creation-SNAPSHOT.zip)
=> fix: handle endpoint url containing underscore

gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/client/WebSocketConnectorClientFactory.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/client/WebSocketEndpoint.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/test/java/io/gravitee/exchange/connector/websocket/client/WebSocketEndpointTest.java
When deploying a Controller in Kubernetes behind an Ingress, the URL to configure in the Connector's side may contain a path (so the Ingress can redirect to the proper service)
---
- use it directly by updating your project with version: `1.3.0-accept-path-prefix-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.3.0-accept-path-prefix-SNAPSHOT/gravitee-exchange-1.3.0-accept-path-prefix-SNAPSHOT.zip)
=> feat(connector): handle URL containing a path

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/controller/ExchangeController.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/controller/listeners/TargetListener.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/DefaultExchangeController.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelEvictedEvent.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelManager.java
Controller exposes methods to (un)register listeners. Those listeners should implement TargetListener interface.
A new event for primary channel evictions is added. The event is listened for in DefaultExchangeController, and when triggered, invokes the 'onPrimaryChannelEvicted' method on all relevant TargetListeners.
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `1.4.0-support-listener-primary-evicted-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee- …
=> feat(controller): register listener to listen primary channel eviction

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/channel/AbstractWebSocketChannel.java
Small PR to track internal error and return valid reply to the sender.
---
- use it directly by updating your project with version: `1.2.4-handle-internal-handler-error-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.2.4-handle-internal-handler-error-SNAPSHOT/gravitee-exchange-1.2.4-handle-internal-handler-error-SNAPSHOT.zip)
=> fix: handle internal error when handling command

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/channel/AbstractWebSocketChannel.java
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `1.4.2-add-missing-throwable-on-warn-log-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.4.2-add-missing-throwable-on-warn-log-SNAPSHOT/gravitee-exchange-1.4.2-add-missing-throwable-on-warn-log-SNAPSHOT.zip)
=> fix: add throwable to internal error warn log

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/channel/AbstractWebSocketChannel.java
**Issue**
This is how it looks today in Cockpit `preprod`. Lot of noise for an "expected" behaviour
Only log a message when there was actually a configured timeout.
This avoids logging unnecessary message for legacy HEALTH_CHECK commands.
---
- use it directly by updating your project with version: `1.5.1-fix-warn-timeout-message-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.5.1-fix-warn-timeout-message-SNAPSHOT/gravitee-exchange-1.5.1-fix-warn-timeout-message-SNAPSHOT.zip)
=> fix: avoid warn log when the timeout is inevitable

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/command/CommandStatus.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/command/DefaultExchangeSerDe.java, gravitee-exchange-api/src/test/java/io/gravitee/exchange/api/websocket/command/DefaultExchangeSerDeTest.java
**Issue**
[Link to the original issue](https://gravitee.atlassian.net/browse/CJ-1802)
Add default value for unknow command status in order to support old FAILURE value.
---
- use it directly by updating your project with version: `1.5.2-CJ-1802-Fallback-to-default-status-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.5.2-CJ-1802-Fallback-to-default-status-SNAPSHOT/gravitee-exchange-1.5.2-CJ-1802-Fallback-to-default-status-SNAPSHOT.zip)
=> fix: set default enum value for CommandStatus

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/channel/Channel.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/controller/metrics/ChannelMetric.java, gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/channel/AbstractWebSocketChannel.java, gravitee-exchange-controller/gravitee-exchange-controller-core/pom.xml, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/ChannelManager.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/cluster/ControllerClusterManager.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/channel/ChannelManagerTest.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/channel/SampleChannel.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelCandidateStoreTest.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelManagerTest.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/cluster/ControllerClusterManagerTest.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/cluster/MultiMemberStandaloneClusterManager.java, gravitee-exchange-controller/gravitee-exchange-controller-embedded/src/main/java/io/gravitee/exchange/controller/embedded/channel/EmbeddedChannel.java
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-211
Implement a mechanism when a new member joins the cluster in order to check if we should rebalance (close with reconnect) channels to properly divide them accross the cluster.
---
- use it directly by updating your project with version: `1.6.0-add-rescalling-mechanism-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.6.0-add-rescalling-mechanism-SNAPSHOT/gravitee-exchange-1.6.0-add-rescalling-mechanism-SNAPSHOT.zip)
=> Add rescalling mechanism

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/configuration/IdentifyConfiguration.java
The log displayed when using a deprecated configuration was missleading and used the generic key property instead of the identified key.
The following :
`[cloud] Using deprecated configuration 'cockpit.truststore.password', replace it with 'connector.ws.ssl.truststore.password' as it will be removed.`
will become
`[cloud] Using deprecated configuration 'cockpit.truststore.password', replace it with 'cloud.connector.ws.ssl.truststore.password' as it will be removed.`
---
- use it directly by updating your project with version: `1.6.1-fix-fallback-log-SNAPSHOT`
- download it from Artifactory …
=> fix: log the identified key instead of the key when using deprecated configuration

gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/cluster/ControllerClusterManager.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/management/ControllerTargetsMetricsEndpoint.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/management/ControllerTargetsMetricsEndpointTest.java
**Issue**
Link to the original issue
Targets endpoint was returning empty array when target doesn't have batchs, by removing the zipWith this PR fixes the issue.
---
- use it directly by updating your project with version: `1.7.5-fix-targets-endpoint-with-batchs-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.7.5-fix-targets-endpoint-with-batchs-SNAPSHOT/gravitee-exchange-1.7.5-fix-targets-endpoint-with-batchs-SNAPSHOT.zip)
=> fix: targets endpoint was returning empty array when target doesn't have batchs

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/channel/AbstractWebSocketChannel.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/DefaultExchangeController.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/ChannelManager.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelCandidateHealthcheckEvent.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelCandidateRegistry.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelManager.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/cluster/ControllerClusterManager.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/channel/ChannelManagerTest.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelManagerTest.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/cluster/ControllerClusterManagerTest.java, gravitee-exchange-controller/gravitee-exchange-controller-websocket/src/main/java/io/gravitee/exchange/controller/websocket/WebSocketExchangeController.java, gravitee-exchange-controller/gravitee-exchange-controller-websocket/src/main/java/io/gravitee/exchange/controller/websocket/WebSocketRequestHandler.java, gravitee-exchange-controller/gravitee-exchange-controller-websocket/src/main/java/io/gravitee/exchange/controller/websocket/server/WebSocketControllerServerVerticle.java, pom.xml
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-391
The PR attempts to fix an issue when a controller node crashes when dealing with some Event. The result is that caches can be inconsistent and lead to errors.
The following mechanism has also been implemented:
- When a cluster member is leaving, we must ensure that all known candidates are still connected.
- The mechanism use :
- a topic where channel candidate health check event will be sent and received by all controllers on the cluster
- each controller depending on its locally connected channel will respond to a dynamic response queue
- the node at the original of the health check event will publish a ChannelEvent message accordingly
- if no response is received before the defined delay, the channel is discarded …
=> Archi 391 fix channel status consistency

pom.xml
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-391
Just use latest version.
---
- use it directly by updating your project with version: `1.8.1-archi-391-bump-node-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.8.1-archi-391-bump-node-version-SNAPSHOT/gravitee-exchange-1.8.1-archi-391-bump-node-version-SNAPSHOT.zip)
=> fix: bump node version to 6.0.3

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/channel/AbstractWebSocketChannel.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/ChannelManager.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/main/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelManager.java, gravitee-exchange-controller/gravitee-exchange-controller-core/src/test/java/io/gravitee/exchange/controller/core/channel/primary/PrimaryChannelManagerTest.java
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-391
This PR attempts to fix an issue occurring in some cases, when nodes come and leave., ThreadBlocked exception could occur when dealing with internal cache and queue. 
For example :
```
io.vertx.core.VertxException: Thread blocked
at com.hazelcast.internal.serialization.impl.compact.RabinFingerprint.<clinit>(RabinFingerprint.java:29)
at com.hazelcast.internal.serialization.impl.compact.Schema.init(Schema.java:129)
at com.hazelcast.internal.serialization.impl.compact.Schema.<init>(Schema.java:57)
at com.hazelcast.internal.serialization.impl.compact.SchemaWriter.build(SchemaWriter.java:52)
at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.buildSchema(CompactStreamSerializer.java:397)
at …
```
=> Archi 391 handle thread blocked

gravitee-exchange-api/src/main/java/io/gravitee/exchange/api/websocket/channel/AbstractWebSocketChannel.java
For debugging purpose, a new TRACE log is added to log the payload sent through the socket.
---
- use it directly by updating your project with version: `1.8.3-trace-command-sent-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.8.3-trace-command-sent-SNAPSHOT/gravitee-exchange-1.8.3-trace-command-sent-SNAPSHOT.zip)
=> fix: add trace logging the payload sent through the socket

gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/WebSocketExchangeConnector.java, gravitee-exchange-connector/gravitee-exchange-connector-websocket/src/main/java/io/gravitee/exchange/connector/websocket/client/WebSocketClientConfiguration.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-9710
Add auto-reconnection capability to ExchangeConnector
---
- use it directly by updating your project with version: `1.8.4-close-channel-when-websocket-connection-close-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/exchange/gravitee-exchange/1.8.4-close-channel-when-websocket-connection-close-SNAPSHOT/gravitee-exchange-1.8.4-close-channel-when-websocket-connection-close-SNAPSHOT.zip)
=> fix: add auto-reconnection capability to ExchangeConnector
